Sprint 14 for review
TerentevOleg/java-shareit pull request #2
Opened 2023-01-17 21:30 UTC by TerentevOleg

2023-01-19 13:22 UTC, alexache requested changes

2023-01-19 13:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Эта аннотация включает в себя @EqualsAndHashcode, которая недопустима для JPA моделей

2023-01-19 13:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (state) {
(опционально) может быть будет удобнее завести енам для стейтов

2023-01-19 13:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User booker = getUser(userId);
(опционально) можно передавать booker и item как аргументы в bookingMapper.fromDto() чтобы получать полноценный обхект одним вызовом. Если это сложнее сделать с mapstruct, то можно пропустить

2023-01-19 13:22 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Повторный комментарий про @Data и JPA entity

2023-01-19 17:40 UTC, TerentevOleg commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
Исправлено

2023-01-19 17:40 UTC, TerentevOleg commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (state) {
Вынес стейты в енам

2023-01-19 17:40 UTC, TerentevOleg commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Исправлено

2023-01-19 17:43 UTC, TerentevOleg commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User booker = getUser(userId);
Что-то не придумал, как это сделать красиво, получается сложнее, чем сейчас

2023-01-20 10:24 UTC, alexache approved these changes

2023-01-20 15:21 UTC, merged