Add item requests
TerentevOleg/java-shareit pull request #3
Opened 2023-01-22 22:15 UTC by TerentevOleg

2023-01-23 20:19 UTC, alexache requested changes

2023-01-23 20:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +@Validated
Это лишняя аннотация, если уже есть @RestController и @Valid на методе

2023-01-23 20:19 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                .andExpect(content().json(objectMapper.writeValueAsString(bookingBuilder.buildDtoResponse())));
Хорошо бы еще добавить verify на то, что сервис был действительно вызван и однократно

2023-01-23 20:19 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/dto/BookingDtoRequestTest.java
> +    JacksonTester<BookingDtoRequest> jacksonTester;
У полей лучше оставлять модификаторы доступа, даже в тестах

2023-01-23 20:19 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/model/BookingTest.java
> +class BookingTest {
Интересный тест. это только ради проверки метода equals(), который не должен ломать модель JPA?

2023-01-23 20:19 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/model/BookingTest.java
> +        booking1.setStatus(BookingStatus.REJECTED);
Здесь можкт booking2?

2023-01-23 20:19 UTC, alexache commented on src/test/java/ru/practicum/shareit/exception/ErrorHandlerTest.java
> +class ErrorHandlerTest {
Нужно ли выносить эти тесты отдельно от теста контроллера?

2023-01-23 20:19 UTC, alexache commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplIntegrationTest.java
> +public class UserServiceImplIntegrationTest {
Может стоит еще добавить интеграционных тестов на другие сервисы/флоу, можно и по 1-2 тесткейсам там

2023-01-24 10:29 UTC, TerentevOleg commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                .andExpect(content().json(objectMapper.writeValueAsString(bookingBuilder.buildDtoResponse())));
Verify добавлен во все тестовые методы каждого тестового класса.

2023-01-24 10:36 UTC, TerentevOleg commented on src/test/java/ru/practicum/shareit/booking/dto/BookingDtoRequestTest.java
> +    JacksonTester<BookingDtoRequest> jacksonTester;
Всем полям добавлены модификаторы доступа.

2023-01-24 10:39 UTC, TerentevOleg commented on src/test/java/ru/practicum/shareit/booking/model/BookingTest.java
> +class BookingTest {
Да

2023-01-24 10:39 UTC, TerentevOleg commented on src/test/java/ru/practicum/shareit/booking/model/BookingTest.java
> +        booking1.setStatus(BookingStatus.REJECTED);
Исправил

2023-01-24 14:46 UTC, TerentevOleg commented on src/test/java/ru/practicum/shareit/user/service/UserServiceImplIntegrationTest.java
> +public class UserServiceImplIntegrationTest {
Добавлены интеграционные тесты

2023-01-24 17:09 UTC, TerentevOleg commented on src/test/java/ru/practicum/shareit/exception/ErrorHandlerTest.java
> +class ErrorHandlerTest {
Перенесены тесты ErrorHandler в UserController

2023-01-24 20:51 UTC, alexache approved these changes

2023-01-26 10:43 UTC, merged