16 sprint for review
TerentevOleg/java-shareit pull request #4
Opened 2023-02-01 16:46 UTC by TerentevOleg

2023-02-04 22:13 UTC, alexache requested changes

2023-02-04 22:13 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        return super.get("/" + bookingId, userId);
Super не обязательно использовать в таких случаях, в наследнике ведь нет методов с таким названием?

2023-02-04 22:13 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemClient.getById(id, userId);
(опционально) не помешает логгировать операции контроллера/клиента

2023-02-04 22:13 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> -import javax.validation.constraints.NotNull;
Метод checkDates, который ниже, тоже относится к валидаци ям, которые теперь должны быть в гейтвее

2023-02-06 13:28 UTC, TerentevOleg commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        return super.get("/" + bookingId, userId);
Исправлено

2023-02-06 13:28 UTC, TerentevOleg commented on gateway/src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return itemClient.getById(id, userId);
Добавлено логгирование

2023-02-06 13:29 UTC, TerentevOleg commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> -import javax.validation.constraints.NotNull;
Метод валидации checkDates вынесен в gateway и сделан в виде аннотации @BookingValidDate

2023-02-06 22:17 UTC, alexache approved these changes

2023-04-08 18:45 UTC, merged